### ISSUE TITLE
Qt error when execute full_gui.py

### ISSUE THREAD

**Issue by KohinH** [sharppy/SHARPpy#104]
Hello! I installed SHARPpy in Mac, OS X EL Capitan, but got Qt error when I run full_gui.py,
>Qt internal error: qt_menu.nib could not be loaded. The .nib file should be placed in >QtGui.framework/Versions/Current/Resources/  or in the resources directory of your application
>bundle.
>Abort trap: 6
Both Pre-compiled Binary and source code installation resulted in the same.
What should I do to with it? 

Thank you.

**Comment by wblumberg** [comment]
Hi @KohinH .  Thank you for the bug report.  I just recently got this error while installing SHARPpy/PySide on a new version of macOS Sierra.  I am not quite sure what the cause of this error is just yet.  There seems to be some issues associated with the version of PySide that can be downloaded from Anaconda.  I tried finding out if this was a version issue this evening, and didn't have any luck.  I will need to look a little closer into this.

**Comment by KohinH** [comment]
Thank you for your reply. Waiting for your good news!

**Comment by wblumberg** [comment]
Hi @KohinH ...I've found the problem and was able to install PySide onto my computer.  This issue is due to the Qt4 package that is installed during the "conda install pyside" step.  The version has something wrong with it, but I can't seem to figure out what it is exactly, and the Anaconda people don't seem too keen on trying to fix it anytime soon. 

A solution is to download the PySide package from the condo-forge community:

https://anaconda.org/conda-forge/pyside

The command on that page downloaded a version that worked for me.  Try that out.  You may have to reinstall Anaconda on your machine or remove the older version of QT4/PySide that resides in your current Anaconda directory.

Here's the documentation that this is an issue with Anaconda's version of PySide.

https://github.com/ContinuumIO/anaconda-issues/issues/1132

**Comment by wblumberg** [comment]
To help others, this bug has been rectified by the version of PySide you download.  Following the installation instructions in the README to install the conda-forge version should fix this.
