### ISSUE TITLE
Error with mlpcl

### ISSUE THREAD

**Issue by rcucinot** [sharppy/SHARPpy#135]
The mlpcl is not being computed for multiple datasets, including the '14061619.OAX' file included in SHARPpy download. I am receiving a ValueError: arange: cannot compute length. Seems to be breaking at the BRN calculation. 

![error](https://user-images.githubusercontent.com/36900861/37731077-9b7ca83e-2d17-11e8-8f8b-169d7a218096.PNG)

**Comment by wblumberg** [comment]
Hi Rachel...this is quite strange and I'm quite surprised that you found a bug with this routine, even with the packaged file.  Can you tell us a little bit more about the versions of SHARPpy and numpy you're using?  We've encountered many problems with the various versions of numpy and this may be a brand new issue.

Thanks!

- Greg

**Comment by rcucinot** [comment]
Hi Greg,
numpy version: 1.14.1
sharppy version: 1.3.0

Thanks,
Rachel

**Comment by wblumberg** [comment]
Are you running with conda?  Can you try downgrading numpy to v1.12.1?

If you're not familiar with the command (although it seems like you've dug though the code well enough), you'll need to use the command "conda install numpy=1.12.1".

**Comment by rcucinot** [comment]
Downgrading fixed the problem! Thank you so much for you time :)

**Comment by wblumberg** [comment]
You're welcome!  Thank you for letting us know.  Hope despite this the program is working well for you!

**Comment by Silviameteoro** [comment]
Hi wblumberg,

I am having a similar issue with the mlpcl (see below). 

/usr/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/sharptab/interp.py:53: RuntimeWarning: divide by zero encountered in log10
  return generic_interp_pres(np.log10(p), prof.logp[::-1], prof.hght[::-1])
/usr/lib64/python2.7/site-packages/numpy/lib/function_base.py:2059: UserWarning: Warning: converting a masked element to nan.
  return interp_func([x], xp, fp, left, right).item()
/usr/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/sharptab/winds.py:45: UserWarning: Warning: converting a masked element to nan.
  ps = np.arange(pbot, ptop+dp, dp)
Traceback (most recent call last):
  File "sharppyreaderTESTE.py", line 86, in <module>
    mlpcl = params.parcelx( prof, flag=4 ) # 100 mb Mean Layer Parcel
  File "/usr/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/sharptab/params.py", line 1935, in parcelx
    bulk_rich(prof, pcl)
  File "/usr/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/sharptab/params.py", line 1994, in bulk_rich
    mnlu, mnlv = winds.mean_wind(prof, pbot, p)
  File "/usr/lib/python2.7/site-packages/SHARPpy-1.3.0-py2.7.egg/sharppy/sharptab/winds.py", line 45, in mean_wind
    ps = np.arange(pbot, ptop+dp, dp)
ValueError: arange: cannot compute length


I currently have numpy v. 1.14.2. Unfortunately, I cannot downgrade to numpy v.12.1 since I am working on a server. It might be an issue downgrading the numpy version that is being used by other users. Could you help me on an alternate solution? 
I am working with python 2.7.5 on a Red Hat linux installation. 
Best Regards.
Silvia
