### ISSUE TITLE
Update Anaconda download link

### ISSUE THREAD

**Issue by tennessean** [sharppy/SHARPpy#150]
This isn't necessarily related to SHARPpy the program, but rather something in the README.md file:

While looking at the main README for the SHARPpy program, I decided to try out the Anaconda Python Distribution, specifically the link provided in the quote below:

>The Anaconda Python Distribution can be downloaded here: https://store.continuum.io/cshop/anaconda/

However, when I did so, I kept getting a [Cloudflare 522 error (Connection timed out)](https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522).  So I tried simply going to the main website URL ( located at https://www.continuum.io/), but it redirected to https://www.anaconda.com/.

The main download page is located at this URL:

>https://www.anaconda.com/download/

Thus, the line that provides the link should be rewritten as such:

>The Anaconda Python Distribution can be downloaded here: https://www.anaconda.com/download/

Hopefully, this correction would be helpful for those who want to use the SHARPpy program, especially through Anaconda!

**Comment by CAM-Gerlach** [comment]
I recommend removing that sentence entirely as its essentially redundant, and just embedding the link directly in the previous sentence, like so (with some other corrections/updates):

> Although there are multiple ways to meet these requirements, we recommend you install the Python 3 version of the [Anaconda Python distribution](https://www.anaconda.com/download/).

I strongly recommend Anaconda3 over Anaconda2 due to the fact that SHARPpy is Python 3 compatible now, the fact that Anaconda3 can easily create a Python 2.7 environments if needed, (``conda create -n your-name-here python=2``) while the reverse can be more troublesome, and of course the looming EOL date for Python 2.7. The latter is particularly true for our community, given the scientific Python stack's essentially universal Python 3 adoption and [particularly rapid progress](https://python3statement.org/) toward going Python 3-only, as many major packages like Numpy (upon which SHARPpy depends), Matplotlib, Pandas, IPython, etc. will be dropping Python 2 support for new releases well before the final EOL, or have already done so.
