### ISSUE TITLE
Win10 Issues

### ISSUE THREAD

**Issue by rpdale** [sharppy/SHARPpy#177]
I nuked last week's version that I installed as the upgrade route gave me the readme.md error from before.

On first run I received the QApplication error so removed those two lines. Now a new error:

  File "c:\users\so_dale\miniconda3\lib\site-packages\sharppy-1.4.0a5-py3.6.egg\runsharp\full_gui.py", line 4, in <module>
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling)
AttributeError: type object 'PySide.QtCore.Qt' has no attribute 'AA_EnableHighDpiScaling'

(base) C:\SHARPpy>sharppy

Traceback (most recent call last):
  File "C:\Users\so_dale\miniconda3\Scripts\sharppy-script.py", line 11, in <module>
    load_entry_point('SHARPpy==1.4.0a5', 'console_scripts', 'sharppy')()
  File "c:\users\so_dale\miniconda3\lib\site-packages\sharppy-1.4.0a5-py3.6.egg\runsharp\full_gui.py", line 1224, in main
    main_win = Main()
  File "c:\users\so_dale\miniconda3\lib\site-packages\sharppy-1.4.0a5-py3.6.egg\runsharp\full_gui.py", line 867, in __init__
    self.__initUI()
  File "c:\users\so_dale\miniconda3\lib\site-packages\sharppy-1.4.0a5-py3.6.egg\runsharp\full_gui.py", line 885, in __initUI
    self.grab().save('./screenshot.png', 'png')
AttributeError: 'Main' object has no attribute 'grab'

I download the 64-bin Win zip file (nice icon!) and it does not start. 

Fatal Error Detected

"Failed to execute script pyi_rth_certifi"

**Comment by wblumberg** [comment]
Thanks for the compliment about the icon! @rpdale 

Windows 10 issues are documented in Issue #176 , so please repost this there so we can keep similar issues together.  See Issue #174 for issue submission guidelines as we want to keep the number of threads condensed.  As for your AttributeErrors, they are very likely due to conflicts where Conda qtpy is linking to your PySide installation instead of PySide2.  I'm not sure how to fix your issue - qtpy should prioritize PySide2 over the previous versions.  Try removing PySide and see if that fixes it.

**Comment by iaraUM** [comment]
I have same issue with the executable version "Failed to execute script pyi_rth_certifi".
Can make a update without needed connection to internet for start sharppy (full_gui.py) as the version 1.3.0 . I have slow connection but i can download the bufkit by my count and open with sharppy.

**Comment by rpdale** [comment]
I totally deleted Miniconda, reinstalled, started Sharppy Andover install from scratch, and then I could run the Win10 binary. Still can't run Sharppy from the Miniconda prompt though :)

I had zero issues at all on my home machine there may some permissions things going on here too.
