### ISSUE TITLE
SARS interactivity

### ISSUE THREAD

**Issue by wblumberg** [sharppy/SHARPpy#19]
Ability to click and load up the tier-1 SARS sounding matches next to the primary sounding in the SHARPpy GUI.

**Comment by keltonhalbert** [comment]
Currently working on this interactivity. 

Something to think about is how we store the SARS data. Right now, I am just going to push all of the sounding files into a folder structure and do it that way. However, we may want to consider something like an NPZ file with a dictionary as a better way of storing this sort of database data. I'm open to suggestions.

**Comment by keltonhalbert** [comment]
Alright!

Rudimentary SARS interactivity has been implemented! You should be able to click on a supercell/hail analogue, and it will display it with the current profile. Currently, there is no combined display for the wind barbs/hodograph yet, but that should be relatively easy to fix in the near future (i.e. sometime this week).

Currently, there are only two bugs that I know of, and they are not directly related to code that I added. If a selected profile does not display, the terminal prompt has given 2 different reasons. One, the io qc tools don't like the data and say it's malformed. Since these are SPC files, I doubt they are malformed, and this should be checked. The other time it breaks is when it can't read a certain file properly, and I have not investigated why just yet, but these tend to be files with pre-2000 dates.

![sars](https://cloud.githubusercontent.com/assets/1411265/6995922/9a793bee-db2d-11e4-9e85-10196cc5b4a0.png)

**Comment by keltonhalbert** [comment]
@wblumberg had suggested a more contrasting color, which I agree with, so I've made a demo of what it would look like if we used the purple color SPC uses when displaying two profiles at once. I'd say this is a lot better. The challenge is that this is using the same framework as the SREF drawing, and SREF probably shouldn't be purple too. Some re-writing and structuring of the SkewT widget will be needed to properly handle this. 
![sars_purple](https://cloud.githubusercontent.com/assets/1411265/6996019/4eaefaea-db33-11e4-8ee7-f02ff670056c.png)

**Comment by keltonhalbert** [comment]
Another purple... 
![sars_purple2](https://cloud.githubusercontent.com/assets/1411265/6996092/bda52430-db36-11e4-8bc4-055741a6ec74.png)

**Comment by wblumberg** [comment]
Here's a list of similar colors to the ones used in SHARP:

#6666CC (visually looks the most similar)
#666699
#333366

**Comment by keltonhalbert** [comment]
Using #6666CC...

(side note: that was one heck of a good analogue there...)
![sars_purple3](https://cloud.githubusercontent.com/assets/1411265/6996123/b7c5f35c-db39-11e4-82e3-f1ef4fe9145e.png)

**Comment by wblumberg** [comment]
Haha.  Nice!  I think that color is my favorite of them all.  It pops out, but not too much.

**Comment by keltonhalbert** [comment]
I like this one the most too.

All that's left until this can be closed: 
1) Hodograph
2) Prevent it from disappearing when switching out parcels
3) Keep making sure it doesn't crash

Once that's done, I will close this thread.
Things to work on in future:
Profile "swapping"
IO problems regarding SARS files

**Comment by keltonhalbert** [comment]
Closing this sucker.
