### ISSUE TITLE
Feature Request: Day of week on title

### ISSUE THREAD

**Issue by rpdale** [sharppy/SHARPpy#43]
It would be nice to have the day of the week in the upper-left, maybe between the timestamp and the () model info?
![capture](https://cloud.githubusercontent.com/assets/11564694/6801519/bdd20504-d1fe-11e4-97c4-71c326935dd5.PNG)

**Comment by keltonhalbert** [comment]
I know that @tsupinie has worked on implementing some user configuration type files that save settings (such as what insets you use) in a behind the scenes format. Perhaps something could be included to allow users to specify some sort of regex for the sounding titles that could be changed through the GUI? 

Obviously the easier solution is just to hardcode the day of the week, but I'm thinking long term - what if other people desire other titles? Thoughts @wblumberg and Tim?

**Comment by wblumberg** [comment]
One idea I've been tossing around is working on a settings box for the picker that would allow you to change such a thing, especially since it's easy to pass a custom string using the % signs.  This would also allow other things to be set easily, like default stations, etc.  That's what I was thinking for solving this problem.

**Comment by wblumberg** [comment]
After reviewing this, I'm not sure adding the day of the week would be prudent.  It would take up space in the title area which is needed for the other titles if soundings are overlaid.  skew.py would be the place to revise this if others would like to so!
