### ISSUE TITLE
tephigram plot type

### ISSUE THREAD

**Issue by zdufran** [sharppy/SHARPpy#79]
I would like to request that a new plot type, tephigrams, be added to SHARPpy.  I looked through the list of issues and did not see that anyone had previously requested this feature.  Many users that were trained by British prefer this view of thermodynamic data.  How feasible would this be?

**Comment by tsupinie** [comment]
Hmm. Well, the short answer is "I'm not sure." I've never tried to code a tephigram plotter before, so I'm not sure how hard the transformations are to get right. I have thought about having an option for different thermodynamic diagrams, but it never progressed much beyond the "yeah, that might be cool" stage. Since there's some demand for it, I'll consider adding it to the list of user-specifiable options I'm currently working on.

**Comment by keltonhalbert** [comment]
I think this is something that can be done, it's more of a question of how.

In theory, it shouldn't be too difficult to either a) modify the current Skew-T window to change axes to a tephigram or B, code up a new inset that can be swapped out for the Skew-T inset. Is this something where the remaining windows and displays are desired to remain, or are you thinking along the lines of a completely different layout? Obviously the first is the more general and feasible option, but trying to get an idea of what direction this could lead.

**Comment by zdufran** [comment]
Thanks for your response, keltonhalbert.  Sorry for my slow response...

I don't think a completely different layout is necessary.  Tephigrams relay the same information, just in a little different layout of axes, so I think all of the other capabilities and indices, etc can stay the same.

What is the likelihood of adding tephigrams to SHARPpy?

**Comment by wblumberg** [comment]
@zdufran would you be able to provide any transformation equations to do the plotting for tephigrams?  I started trying to do this the other day and ended up getting wrapped up in the math.

**Comment by wblumberg** [comment]
Closing this because this thread seems dead.
