### ISSUE TITLE
One issue and an enhancement

### ISSUE THREAD

**Issue by msuwx1** [sharppy/SHARPpy#81]
One question I have is I have seen on the instructions for analog soundings for the new beta version but when I download the executable file for Windows, I do not see any chance to see analog soundings. Any idea why I can't see those and what needs to be done to see that? I had previously installed using Conda but the executable seemed the way to go, unless I can't get the analog soundings, if there is a way to add it otherwise.

Also, I was wondering if there was a way to load in archived soundings (usually much older than the requested database from SPC that may only be about 7-8 days I've seen on SharpPy). 

I know that we have some archived NSharp files but after looking at some of the internal request XML files for the soundings, I see its pulling straight from the SPC database which I know goes back into the 1950s. Question I have is how would I load in an archived sounding, such as what format would it need to be in? Also would there be any type of enhancement to pull down a date and it request the sounding and download into SharpPy from the server there at the SPC? Another option would be for us to load in our archived NSharp files and convert them to the correct format and load into SharpPy, somehow.

Any ideas?

Thanks,

David

**Comment by wblumberg** [comment]
Hi David...

We're all coming off of our semester, so we can provide a little more support than we have in the last few months!  In our current version, the analog soundings are from the SARS (Sounding Analog Retrieval System), which are a hand picked proximity sounding database generated at SPC.  So with the executable, the analog soundings from the SARS database are kept buried within the executable file.  When the SARS "quality matches" (e.g. 99050400OUN TOR) pop up, you can click on them to load them into the GUI for visual comparison.  When you don't use the executable and install from the source code, you can get at those files a little easier.  

Although as developers we have access to the full historical database, we cannot share it through SHARPpy, so we are only restricted to observed soundings hosted on the SPC web server.  However, specific archived soundings you have saved can be loaded on demand.  You'll have to follow the instructions in the README listed underneath "Loading in Archived Data Files".  This includes information about the data format you'll need to convert your NSHARP files too in order to have SHARPpy load them into the GUI.

Hope this helps!  

Greg
