### ISSUE TITLE
How to customize SHARPpy?

### ISSUE THREAD

**Issue by dave2004NMC** [sharppy/SHARPpy#88]
Hi, guys:
    I want to customize SHARPpy for East Asia region. Adding new data source is feasible with local XML file. However, how is it possible that "Select Sounding Source" in GUI only show the customized data source without default sources? And I also want to change the "Select Map Area" to East Asia. How can I achieve this. Very thanks!
      Dave

**Comment by keltonhalbert** [comment]
Hi Dave,

The "Select Sounding Source" is populated by the XML files contained in the .sharppy/datasources directory. If you delete all the extra XML files, it will only display the datasources you define.

As far as the "Select Map Area", @tsupinie would know more about how to do that since he's done most of the writing on that end.

**Comment by tsupinie** [comment]
Dave,

When you open up the picker window, you should be able to click and drag the map and double-click to re-center on a particular point and re-orient the map such that north is up.  For technical reasons that will be fixed in the next version, re-orienting takes a couple seconds after the double click. The scroll wheel zooms in and out. Once you've got the map how you want it, click the "Save Map View as Default" button in the very upper right corner. That should save that particular view so that next time you open SHARPpy, that will be your default view.

Does that help?
