### ISSUE TITLE
MAC Binary problem and few indications on  plotted lines

### ISSUE THREAD

**Issue by guidocioni** [sharppy/SHARPpy#89]
Hi, I was using SHARPPy a few months ago and now I decided to give it another shot. I noticed that the MacOs binary provided doesn't work since it is recognized as malware and there's no way to disable this protection. However, installing from source code works. 
After having installed the software I was trying to plot some old soundings using the "open" feature. Everything works pretty well but I don't know what most of the lines are indicating: I searched into the documentation many times but was unable to found the relative description. I understand that red and green are temperature and dewpoint, respectively. Then, what are:
-dashed red line
-light blue line 
-purple dashed line
In particular, regarding the dashed red line, it seems that surface parcel ascent is done by considering the surface temperature resulting from this red dashed line, which is not the real one... 

![prova](https://cloud.githubusercontent.com/assets/12760310/12943810/0fa80fb6-cfe4-11e5-972b-d296f97a3897.png)

**Comment by tsupinie** [comment]
Have you tried right-clicking (shift-clicking) on the binary and choosing the "Open" option? Either from the dock or from Finder? How about after the OS telling you it thinks SHARPpy is malware, opening System Preferences and clicking on "Privacy and Security"? There should be a box in there to let you open SHARPpy anyway. We promise it isn't malware. :)

As for the lines, I guess we assumed a certain familiarity with the SPC sounding plots when writing the documentation. Maybe it would be good to add a paragraph in there about the lines.  The dashed red line is the virtual temperature trace, the solid cyan line is the wet bulb temperature trace, and the dashed magenta line is the downdraft parcel trace (used for computing DCAPE).  

The virtual temperature is used for the surface-based parcel instead of the actual temperature because it better represents buoyancy than the actual temperature. By the same token, buoyancy is computed against the virtual temperature trace, not the actual temperature trace.
